/**
 * @file app.config.ts
 * @description Per-game visual identity. Generated by tools/propagate-theme.js.
 * Edit the source script and re-run to update.
 */
export const APP_CONFIG = {
  name: "Kdoub",
  primary: "#C084FC",
  secondary: "#7C3AED",
  splash: {
    glow: "rgba(192,38,211,0.6)",
    sallyGlow: "rgba(124,58,237,0.8)",
    pillBorder: "rgba(192,132,252,0.5)",
    pillBg: "rgba(124,58,237,0.15)",
    pillText: "#E9D5FF",
    suit: "♠",
    suit2: "♣",
  },
  slides: {
    slide2: { tint: ["rgba(124,58,237,0.55)","rgba(192,38,211,0.7)","rgba(10,10,26,0.95)"], variant: "fan" },
    slide3: { tint: ["rgba(192,132,252,0.45)","rgba(30,27,75,0.85)","rgba(10,10,26,0.95)"], variant: "scattered" },
    slide4: { tint: ["rgba(245,158,11,0.45)","rgba(124,58,237,0.7)","rgba(10,10,26,0.95)"], variant: "spread" },
  },
} as const;

export type SlideVariant = 'fan' | 'scattered' | 'spread' | 'grid';
